INSERT INTO `projeto_integrado`.`Aeroporto` (`descricao`, `sigla`, `endereco`) VALUES
('Aeroporto Internacional de São Paulo - Guarulhos',                'GRU', 'Rod. Hélio Smidt, s/nº - Cumbica, Guarulhos - SP, 07190-100'),
('Aeroporto de Congonhas - São Paulo',                              'CGH', 'Av. Washington Luís, s/nº - Vila Congonhas, São Paulo - SP, 04626-911'),
('Aeroporto Internacional de Brasília - Brasília',                  'BSB', 'Lago Sul, Brasília - DF, 71608-900'),
('Aeroporto Internacional Antônio Carlos Jobim - Rio de Janeiro',   'GIG', 'Av. Vinte de Janeiro, s/n° - Galeão, Ilha do Governador, Rio de Janeiro - RJ, 21941-570'),
('Aeroporto Internacional de Viracopos - Campinas',                 'VCP', 'Aeroporto Internacional de Viracopos - Campinas'),
('Aeroporto Internacional de Confins - Belo Horizonte',             'CNF', 'Rod. MG 10, KM 39 - Confins, Belo Horizonte - MG, 33500-900'),
('Aeroporto Santos Dumont - Rio de Janeiro',                        'SDU', 'Pça. Sen. Salgado Filho, s/n - Centro, Rio de Janeiro - RJ, 20021-340'),
('Aeroporto Internacional de Salvador - Salvador',                  'SSA', 'Pça. Gago Coutinho, s/n - São Cristóvão, Salvador - BA, 41520-970'),
('Aeroporto Internacional Salgado Filho - Porto Alegre',            'POA', 'Av. Severo Dulius, 90.010 – São João – Porto Alegre – RS'),
('Aeroporto Internacional de Fortaleza - Fortaleza',                'FOR', 'Av. Senador Carlos Jereissati, 3000 - Serrinha, Fortaleza - CE, 60741-900'),
('Aeroporto Internacional do Recife - Recife',                      'REC', 'Pça. Ministro Salgado Filho, s/nº - Imbiribeira, Recife - PE, 51210-902'),
('Aeroporto Internacional de Curitiba - Curitiba',                  'CWB', 'Av. Rocha Pombo - Águas Belas, São José dos Pinhais - PR, 83010-900'),
('Aeroporto Internacional de Manaus - Manaus',                      'MAO', 'Av. Santos Dumont, 1350 - Tarumã, Manaus - AM, 69041-000'),
('Aeroporto Internacional Governador Aluízio Alves - Natal',        'NAT', 'Av. Ruy Pereira dos Santos, 3100 - São Gonçalo do Amarante, Natal - RN, 59290-000'),
('Aeroporto Internacional de Belém - Belém',                        'BEL', 'Av. Júlio César, s/n - Val-de-Cans, Belém - PA, 66115-970'),
('Aeroporto Internacional Zumbi dos Palmares - Maceió',             'MCZ', 'Rod. BR 104, Km 91, Tabuleiro do Pinto, Maceió - AL, 57110-100'),
('Aeroporto Internacional de São Luís - São Luís',                  'SLZ', 'Av. dos Libaneses, 3503 - Bairro Tirirical, São Luís - MA, 65056-480'),
('Aeroporto Internacional Hercílio Luz - Florianópolis',            'FLN', 'Av. Dep. Diomício Freitas, 3393 - Carianos, Florianópolis - SC, 88047-900'),
('Aeroporto Internacional Marechal Rondon - Cuiabá',                'CGB', 'Av. João Ponce de Arruda, s/n - Jardim Aeroporto, Várzea Grande - MT, 78110-900'),
('Aeroporto Internacional de Campo Grande - Campo Grande',          'CGR', 'Av. Duque de Caxias, s/n - Vila Serradinho, Campo Grande - MS, 79101-901'),
('Aeroporto Internacional Cataratas - Foz do Iguaçu',               'IGU', 'BR 469 - Km 16,5 - Foz do Iguaçu - Paraná Aeroporto'),
('Aeroporto Internacional de Bayeux - João Pessoa',                 'JPA', 'Aeroporto Internacional Presidente Castro Pinto , s/n , Jardim Aeroporto, Bayeux - PB'),
('Aeroporto Internacional de Aracaju - Aracaju',                    'AJU', 'Av. Senador Júlio Cesar Leite - Santa Teresa, Aracaju - SE, 49037-580'),
('Aeroporto Santa Genoveva - Goiânia',                              'GYN', 'Pça. Cap. Frazão, 913 - Santa Genoveva, Goiânia - GO, 74672-410');
